P8105 Homework 3 Solution
================
Xun Wang
10/14/2019

This file is the solution to P8105 Homework 3 from Xun Wang (xw2417).

Besides loading `library` in the beginning, I also include figure
preferences in global options as this code chunk.

``` r
library(tidyverse)

knitr::opts_chunk$set(
  echo = TRUE，
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%")

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

## Problem 1

This problem uses the *Instacart* dataset.

#### 1.1 Read datasets from Github

The code chunk below reads the dataset *instacart* from Github package
*p8105.datasets*.

``` r
library(p8105.datasets)
data("instacart")
janitor::clean_names(instacart)
```

    ## # A tibble: 1,384,617 x 15
    ##    order_id product_id add_to_cart_ord~ reordered user_id eval_set
    ##       <int>      <int>            <int>     <int>   <int> <chr>   
    ##  1        1      49302                1         1  112108 train   
    ##  2        1      11109                2         1  112108 train   
    ##  3        1      10246                3         0  112108 train   
    ##  4        1      49683                4         0  112108 train   
    ##  5        1      43633                5         1  112108 train   
    ##  6        1      13176                6         0  112108 train   
    ##  7        1      47209                7         0  112108 train   
    ##  8        1      22035                8         1  112108 train   
    ##  9       36      39612                1         0   79431 train   
    ## 10       36      19660                2         1   79431 train   
    ## # ... with 1,384,607 more rows, and 9 more variables: order_number <int>,
    ## #   order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

**Comments:** The *instacart* dataset read from Github is cleaned by
`janitor::clean_names`. The *instacart* dataset has 1384617 rows and 15
columns. The **key** variables are the *order\_id* and *product\_id*.
For example, in order 1 ordered by user 112108, Bulgarian Yogurt
(product 49302) was the first to be added to the cart. This was the 4th
time the user placed an order and this product was reordered by the
user. The order was placed on Thursday between 10-11 am, 9 days after
the user’s last purchase. This product was placed at *yogurt* aisle
(aisle\_id 120) in the *dairy & eggs* department (department\_id 16).

#### 1.2 *instacart* data analysis

## Problem 2

## Problem 3
